version: "3"

services:
  registry:
    image: registry:2
    ports:
      - 5000:5000
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - registry-data:/var/lib/registry
      - registry-certs:/certs
      - registry-auth:/auth
    networks:
      - proxy
    deploy:
      replicas: 1
      placement:
        constraints: 
          - node.role == worker
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.port=5000
        - com.df.serviceDomain=portainer.YOURIP.nip.io

volumes:
  registry-data:
    driver: rexray/cinder:latest
  registry-certs:
    driver: rexray/cinder:latest
  registry-auth:
    driver: rexray/cinder:latest

networks:
  proxy:
    external: true

