version: '2'
services:
  varnish:                
    image: pblaas/varnish4
    ports:   
      - "80:80/tcp"  
      - "6083:6083/tcp"
    environment:
      - "BACKENDHOST=HOST_DOMAIN_LTD"
      - "BACKENDPORT=80"
      - "CACHE_SIZE=256m"
  hitch:
    image: pblaas/hitch
    ports:
      - "443:443/tcp"
    depends_on:
      - varnish 
    links:
      - varnish
    environment:
      - "BACKENDHOST=[varnish]:80"
    volumes:
      - /root/cert.pem:/sslcerts/concat.pem

